// AUTO-GENERATED by scripts/_build-cb-anchors.mjs — do not edit by hand.
// Edge-safe bundled CB/ACT exemplars (real official-test items, extracted from
// data/cb-corpus). The full corpus loader (cb-corpus.ts) is fs-based / Node-only;
// this compact subset lets the LIVE (Cloudflare edge) generator ground on real
// CB/ACT items too — the #1 fidelity lever. Regenerate when the corpus changes.

export type AnchorSection = "READING_WRITING" | "MATH" | "ACT_ENGLISH" | "ACT_READING" | "ACT_SCIENCE";
export interface CbAnchor { stem: string; options: Record<string, string>; }

export const CB_CORPUS_ANCHORS: Record<AnchorSection, CbAnchor[]> = {
  "READING_WRITING": [
    {
      "stem": "In February 1919, following the end of the First World War, women from ten countries around the world convened the Inter-Allied Women's Conference in Paris. The conference's goals were _______ ensure women's participation in the proceedings of the Paris Peace Conference, to secure the right of women to serve in the League of Nations, and to advocate for human rights. Which choice completes the text so that it conforms to the conventions of Standard English? A) threefold: to B) threefold. To C) threefold to D) threefold; to - 24 - - Mathematician Grigori Perelman, sometimes in conjunction with mathematicians Richard S. Hamilton and Shing-Tung Yau, _______ credited with proving the Poincar� conjecture. Having built on Hamilton's previous work to solve the proof, Perelman has insisted that Hamilton receive credit. Yau later found and closed ",
      "options": {
        "A": "are",
        "B": "have been",
        "C": "are being",
        "D": "is"
      }
    },
    {
      "stem": "The following text is adapted from Lewis Carroll's 1889 satirical novel Sylvie and Bruno. A crowd has gathered outside a room belonging to the Warden, an official who reports to the Lord Chancellor. One man, who was more excited than the rest, flung his hat high into the air, and shouted (as well as I could make out) \"Who roar for the Sub-Warden?\" Everybody roared, but whether it was for the Sub-Warden, or not, did not clearly appear: some were shouting \"Bread!\" and some \"Taxes!\", but no one seemed to know what it was they really wanted. All this I saw from the open window of the Warden's breakfast-saloon, looking across the shoulder of the Lord Chancellor. \"What can it all mean?\" he kept repeating to himself. \"I never heard such shouting before--and at this time of the morning, too! And with such unanimity!\" Based on the text, how does t",
      "options": {
        "A": "He asks about the meaning of the crowd's shouting, even though he claims to know what the crowd wants.",
        "B": "He indicates a desire to speak to the crowd, even though the crowd has asked to speak to the Sub-Warden.",
        "C": "He expresses sympathy for the crowd's demands, even though the crowd's shouting annoys him.",
        "D": "He describes the crowd as being united, even though the crowd clearly appears otherwise."
      }
    },
    {
      "stem": "Sociologist Alton Okinaka sits on the review board tasked with adding new sites to the Hawai`i Register of Historic Places, which includes Pi`ilanihale Heiau and the `paeka`a Road Bridge. Okinaka doesn't make such decisions _______ all historical designations must be approved by a group of nine other experts from the fields of architecture, archaeology, history, and Hawaiian culture. Which choice completes the text so that it conforms to the conventions of Standard English? A) single-handedly, however; B) single-handedly; however, C) single-handedly, however, D) single-handedly however -- - ~ 27- - ~ In 1968, US Congressman John Conyers introduced a bill to establish a national holiday in honor of Dr. Martin Luther King Jr. The bill didn't make it to a vote, but Conyers was determined. He teamed up with Shirley Chisholm, the first Black w",
      "options": {
        "A": "Instead,",
        "B": "Likewise,",
        "C": "Finally,",
        "D": "Additionally,"
      }
    }
  ],
  "MATH": [
    {
      "stem": "In right triangle RST , the sum of the measures of angle R and angle S is 90 degrees. The value of 15 sin(R) is 4 . What is the value of cos(S) ? 15 A) 15 15 B) 4 4 15 C) 15 D) 15 -16 - y 50 40 \\. gi::Q 30 ~ \\ s0.. uo 20 \\ \\ 10 \\ I\\ '~ u X 10 20 30 40 50 6 ) 70 80 90 100 Company A The graph shows the relationship between the number of shares of stock from Company A, x, and the number of shares of stock from Company B, y, that Simone can purchase. Which equation could represent this relationship?",
      "options": {
        "A": "x - 7 5",
        "B": "8x - 3 2",
        "C": "8x2 - 3x - 14 2x - 14",
        "D": "8x2 - 3x - 77 2x - 14"
      }
    },
    {
      "stem": "A total of 165 people contributed to a charity event as either a donor or a volunteer. 130 people contributed as a donor. How many people contributed as a volunteer? A) 35 B) 130 C) 165 D) 330 -2 ~ There are 250 trees in a park. Of these trees, 6% are birch trees. How many birch trees are in the park? A) 6 B) 15 C) 75 D) 244 -3 ---- y '\\ \\ \\ \\ \\ \\ 12 11 10 9 8 7 6 5 \\4 \\3 \".(, I I I I I I I J I / 1 -2 f X 2 The graph of the quadratic function y = f (x) is shown. What is the vertex of the graph?",
      "options": {
        "A": "18",
        "B": "131",
        "C": "149",
        "D": "2,376"
      }
    },
    {
      "stem": "Which expression is equivalent to 8x(x - 7) - 3(x - 7) , where x > 7 ? 2x - 14 A) x - 7 5 B) 8x - 3 2 C) 8x2 - 3x - 14 2x - 14 D) 8x2 - 3x - 77 2x - 14 -19 ~ Keenan made 32 cups of vegetable broth. Keenan then filled x small jars and y large jars with all the vegetable broth he made. The equation 3x + 5y = 32 represents this situation. Which is the best interpretation of 5y in this context?",
      "options": {
        "A": "The number of large jars Keenan filled",
        "B": "The number of small jars Keenan filled",
        "C": "The total number of cups of vegetable broth in the large jars",
        "D": "The total number of cups of vegetable broth in the small jars"
      }
    }
  ],
  "ACT_ENGLISH": [
    {
      "stem": "Which choice most precisely conveys the narrowness of the space?",
      "options": {
        "F": "No Change",
        "G": "sample",
        "H": "sliver",
        "J": "speck"
      }
    },
    {
      "stem": "Which sequence of sentences presents the writer's argument most logically?",
      "options": {
        "A": "No Change",
        "B": "1, 3, 2",
        "C": "2, 3, 1",
        "D": "3, 1, 2"
      }
    },
    {
      "stem": "Which transition word, if any, is most logical in context?",
      "options": {
        "F": "No Change",
        "G": "team, nevertheless,",
        "H": "team, however,",
        "J": "team"
      }
    }
  ],
  "ACT_READING": [
    {
      "stem": "Based on the table, which of the following pairs of materials are most different in terms of elasticity?",
      "options": {
        "F": "Silver garden spider flag silk and high-tensile steel fiber",
        "G": "Silver garden spider flag silk and Kevlar 49 fiber",
        "H": "Domestic silkworm silk and nylon fiber",
        "J": "Kevlar 49 fiber and carbon fiber"
      }
    },
    {
      "stem": "In the context of Passage A, the event described in the second paragraph (lines 26�45) most nearly serves to:",
      "options": {
        "A": "provide an anecdote that illustrates the power of the wind in Brooklyn.",
        "B": "describe the newspaper seller's amusement as the papers were tossed about by the wind.",
        "C": "recount an experience that left the narrator wary of the wind in Brooklyn.",
        "D": "suggest that there are areas of Brooklyn that are intolerable because of the wind."
      }
    },
    {
      "stem": "In the context of the passage, the main function of the first paragraph (lines 1�8) is to:",
      "options": {
        "A": "provide an overview of the internal process that enables spiders to produce different types of silk.",
        "B": "illustrate the strength and versatility of spider silks by describing how one particular spider uses its silks to create a web.",
        "C": "introduce the idea that spiders are resourceful by describing the obstacles they encounter when producing silks for their webs.",
        "D": "point out that the properties of silks made by spiders are similar to those of silks made by other animals."
      }
    }
  ],
  "ACT_SCIENCE": [
    {
      "stem": "Which student would be most likely to agree that while the rod was partially submerged, the scale was supporting the entire weight of the rod?",
      "options": {
        "F": "Student 1",
        "G": "Student 2",
        "H": "Student 3",
        "J": "Student 4"
      }
    },
    {
      "stem": "Based on Scientist 2's argument, do gas particles more likely accrete near the equator or near the poles of a protostar with a disk?",
      "options": {
        "A": "Near the equator, because the effect of RP is increased there.",
        "B": "Near the equator, because the effect of RP is reduced there.",
        "C": "Near the poles, because the effect of RP is increased there.",
        "D": "Near the poles, because the effect of RP is reduced there."
      }
    },
    {
      "stem": "Based on the results of the study, approximately what percent of the seedlings that received a sunlight intensity of 10% survived to 10 weeks?",
      "options": {
        "F": "8%",
        "G": "18%",
        "H": "92%",
        "J": "Cannot be determined from the given information"
      }
    }
  ]
};

/** Format an anchor as a few-shot example block (mirrors cb-corpus.formatAnchorForPrompt). */
export function formatAnchor(a: CbAnchor, idx: number): string {
  const opts = Object.entries(a.options).map(([k, v]) => `  ${k}) ${v}`).join("\n");
  return `EXAMPLE ${idx} (from an official CB/ACT practice test):\nStem: ${a.stem.slice(0, 500)}\nOptions:\n${opts}`;
}
