import type { Metadata } from "next";
import Link from "next/link";
import { Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | StudentNest Prep",
  description: "Terms of Service for StudentNest Prep. Subscription billing, refund policy, AI-generated content disclaimer, and intellectual property.",
};

export default function TermsPage() {
  const sections = [
    {
      id: "acceptance",
      title: "1. Acceptance of Terms",
      body: `By accessing or using StudentNest (studentnest.ai), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform. We may update these terms from time to time; continued use of the service after changes constitutes acceptance of the revised terms.`,
    },
    {
      id: "subscription",
      title: "2. Subscription & Billing",
      body: `StudentNest offers a free tier and a Premium subscription. Premium is billed either monthly ($9.99/month) or annually ($79.99/year). All payments are processed securely by Stripe. StudentNest does not store your credit card number or payment details on our servers — this information is handled entirely by Stripe in accordance with PCI-DSS standards. Subscription charges renew automatically at the end of each billing period unless cancelled before the renewal date.`,
    },
    {
      id: "refunds",
      title: "3. Refund Policy",
      body: `We offer a 7-day money-back guarantee on new Premium subscriptions. If you are not satisfied within 7 days of your first Premium payment, contact us at contact@studentnest.ai and we will issue a full refund — no questions asked. After the 7-day window, subscription payments are non-refundable. You may cancel at any time and will retain Premium access through the end of your paid billing period.`,
    },
    {
      id: "cancellation",
      title: "4. Cancellation",
      body: `You may cancel your Premium subscription at any time from the Billing page within your account. Cancellation takes effect at the end of the current billing period — you will not be charged again, and you will continue to have Premium access until that date. Cancellations do not entitle you to a prorated refund of any unused portion of the subscription period, except as described in our 7-day money-back guarantee above.`,
    },
    {
      id: "ai-content",
      title: "5. AI-Generated Content",
      body: `Practice questions, study plans, tutor responses, and other educational materials on StudentNest are generated by artificial intelligence. This content is created independently and is not sourced from, reproduced from, or affiliated with any official AP®, SAT®, or ACT® materials. AI-generated content may occasionally contain errors. StudentNest is not a replacement for official exam preparation materials from the College Board or ACT, Inc., and we make no guarantee that practicing on this platform will result in any particular exam score.`,
    },
    {
      id: "ip",
      title: "6. Intellectual Property",
      body: `AP®, Advanced Placement®, SAT®, and CLEP® are trademarks registered by the College Board, which is not affiliated with and does not endorse this site. ACT® is a registered trademark of ACT, Inc. These organizations have no involvement in the production of StudentNest content. The StudentNest platform, branding, and original content are owned by StudentNest and may not be reproduced without permission.`,
    },
    {
      id: "liability",
      title: "7. Limitation of Liability",
      body: `StudentNest is provided "as is" without warranties of any kind, express or implied. We do not guarantee uninterrupted service, error-free content, or any specific outcome on standardized exams. To the maximum extent permitted by applicable law, StudentNest and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform, including but not limited to lost scores, missed deadlines, or reliance on AI-generated content.`,
    },
    {
      id: "contact",
      title: "8. Contact & Disputes",
      body: `For billing inquiries, refund requests, or questions about these terms, please contact us at contact@studentnest.ai. We aim to respond to all inquiries within 2 business days. If you believe there is an error with a charge, please contact us before initiating a chargeback — we are happy to resolve billing issues directly.`,
    },
  ];

  return (
    <div className="max-w-3xl mx-auto px-4 py-16 space-y-12">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="flex items-center justify-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-blue-500/20 flex items-center justify-center">
            <Scale className="h-6 w-6 text-blue-500" />
          </div>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>
        <p className="text-muted-foreground">
          Last updated: March 19, 2026
        </p>
        <p className="text-sm text-muted-foreground max-w-xl mx-auto">
          Please read these terms carefully before using StudentNest. By using the platform,
          you agree to the terms described below.
        </p>
      </div>

      {/* Sections */}
      <div className="space-y-8">
        {sections.map((section) => (
          <div
            key={section.id}
            className="rounded-xl border border-border/40 bg-card p-6 space-y-3"
          >
            <h2 className="text-lg font-semibold">{section.title}</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">{section.body}</p>
          </div>
        ))}
      </div>

      {/* Footer note */}
      <div className="text-center space-y-2 pt-4">
        <p className="text-xs text-muted-foreground/70">
          Questions? Email us at{" "}
          <a href="mailto:contact@studentnest.ai" className="underline hover:text-foreground transition-colors">
            contact@studentnest.ai
          </a>
        </p>
        <p className="text-xs text-muted-foreground/50">
          <Link href="/pricing" className="underline hover:text-foreground transition-colors">Pricing</Link>
          {" · "}
          <Link href="/about" className="underline hover:text-foreground transition-colors">About</Link>
        </p>
      </div>
    </div>
  );
}
