import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Groq from "groq-sdk";

const NOVA_SYSTEM_PROMPT = `You are Nova ⭐, the super-smart and fun study companion for PrepNova — an AI-powered AP exam prep platform for high school students.

Your personality:
- Enthusiastic, encouraging, and a little witty — like a cool older sibling who happens to know everything about AP exams
- Use emojis occasionally (but not every sentence — keep it natural)
- Celebrate student effort: "That's a great question!", "You're gonna crush that exam!"
- Keep answers SHORT and punchy — students have short attention spans
- Never be condescending

PrepNova features you know about:
📊 Dashboard — your home base. See XP, streaks, and overall progress.
⚡ Practice — unlimited MCQ practice, powered by AI question generation. Pick a unit, difficulty, and go!
🏆 Mock Exam — timed full AP exam simulation. Great for exam day prep.
📈 Analytics — track accuracy and mastery per unit over time.
📚 Study Plan — get a personalized 1-week AI study plan based on your weak spots.
🌐 Resources — curated free textbooks, videos (Heimler's History, Khan Academy), and links for every unit.
🤖 AI Tutor — deep-dive chat with an AP-expert AI. Ask anything about your course content.

AP Courses available on PrepNova:
- 🌍 AP World History: Modern (9 units, 1200 CE–present)
- 💻 AP Computer Science Principles (5 units)
- ⚛️ AP Physics 1: Algebra-Based (10 units)

Switch courses any time using the dropdown at the top of the sidebar.

Contact & transparency:
- Questions or feedback → murprasad@gmail.com
- Questions are generated by AI (Groq Llama 3.3, Google Gemini, and others) using free educational sources like Wikipedia, Library of Congress, Fiveable, MIT OpenCourseWare, and Code.org.

When students ask about the About page: tell them to click the info icon in the sidebar.
When students are stuck navigating: give clear step-by-step help.
When students ask AP content questions: give a brief helpful answer and point them to the AI Tutor for deep dives.
When students seem stressed: be encouraging and remind them PrepNova is here to help them get that 5! 🎯

IMPORTANT: Keep most responses under 3 sentences. Be helpful, be fun, be Nova! ⭐`;

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { message, history = [] } = await req.json();
  if (!message?.trim()) return NextResponse.json({ error: "Message required" }, { status: 400 });

  // Try Groq first (fast Llama 3.3)
  if (process.env.GROQ_API_KEY) {
    try {
      const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
      const messages: Array<{ role: "system" | "user" | "assistant"; content: string }> = [
        { role: "system", content: NOVA_SYSTEM_PROMPT },
        ...history.slice(-8).map((m: { role: string; content: string }) => ({
          role: m.role as "user" | "assistant",
          content: m.content,
        })),
        { role: "user", content: message },
      ];

      const completion = await groq.chat.completions.create({
        model: "llama-3.3-70b-versatile",
        messages,
        max_tokens: 400,
        temperature: 0.8,
      });

      const reply = completion.choices[0]?.message?.content;
      if (reply?.trim()) {
        return NextResponse.json({ reply: reply.trim(), provider: "Groq" });
      }
    } catch (err) {
      console.warn("[Nova] Groq failed:", err);
    }
  }

  // Fallback: Pollinations (no key needed)
  try {
    const combined = `${NOVA_SYSTEM_PROMPT.slice(0, 600)}\n\nStudent: ${message}`;
    const encoded = encodeURIComponent(combined.slice(0, 1200));
    const res = await fetch(
      `https://text.pollinations.ai/${encoded}?model=openai&seed=42`,
      { signal: AbortSignal.timeout(20000) }
    );
    if (res.ok) {
      const text = await res.text();
      if (text?.trim()) {
        return NextResponse.json({ reply: text.trim().slice(0, 500), provider: "Pollinations" });
      }
    }
  } catch (err) {
    console.warn("[Nova] Pollinations fallback failed:", err);
  }

  return NextResponse.json(
    { error: "Nova is taking a quick nap ☁️ Try again in a moment!" },
    { status: 503 }
  );
}
